development: &development
  adapter: postgresql
  database: admin
  username: admin
  password: 123456
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: admin

production:
  <<: *development
  database: admin